// =============================================================================
// integration_test/quantum_firebase_test.dart
// =============================================================================

import 'dart:convert';
import 'dart:math';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:firebase_core/firebase_core.dart';

// Your exact Firebase Options file generated by FlutterFire CLI
import 'package:quantum_layout/firebase_options.dart'; 

// Your exact Quantum Engine imports
import 'package:quantum_layout/src/plugins/quantum_api_shell.dart';
import 'package:quantum_layout/src/plugins/quantum_api_engine.dart';
import 'package:quantum_layout/src/plugins/quantum_auth_engine.dart';
import 'package:quantum_layout/src/plugins/quantum_sdui_engine.dart';

void main() {
  // 1. Initialize the Integration Test Binding
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  // Helper to prevent test collisions on subsequent runs
  final random = Random();
  String generateRandomId() => DateTime.now().millisecondsSinceEpoch.toString() + random.nextInt(9999).toString();

  final testEmail = 'testuser_${generateRandomId()}@quantum.local';
  final testPassword = 'SuperSecretPassword123!';
  final testCollection = 'test_collection_${generateRandomId()}';

  group('Quantum Enterprise Firebase Integration Tests', () {
    
    setUpAll(() async {
      // 2. Initialize Native Firebase using your project: fast-ability-437320-n7
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );

      // 3. Initialize Quantum Shell in Firebase Mode
      await Quantum.initialize(
        QuantumConfig(
          apiUrl: 'https://firestore.googleapis.com', 
          socketUrl: 'wss://firebase-rtdb',           
          cacheDirectoryPath: '',                     
          driverMode: QuantumDriverMode.firebase, // Connects the Firebase Adapters
          clientSecret: 'TEST_SECRET_KEY_MUST_BE_32_BYTES_LONG_!!!',
          enableOfflineQueueing: true,
        ),
      );
    });

    testWidgets('1. Core Engine Initialization', (WidgetTester tester) async {
      expect(Quantum.isInitialized, isTrue, reason: 'Quantum failed to initialize');
    });

    // =========================================================================
    // AUTHENTICATION ENGINE TESTS
    // =========================================================================
    group('Authentication Engine (FirebaseAuthDriver)', () {
      testWidgets('Register new user with Email/Password', (WidgetTester tester) async {
        final result = await Quantum.auth.register({
          'email': testEmail,
          'password': testPassword,
        });

        expect(result.isSuccess, isTrue, reason: 'Registration failed: ${result.error?.message}');
        
        final session = await Quantum.auth.me();
        expect(session.data['userId'], isNotNull);
        expect(session.data['email'], testEmail);
      });

      testWidgets('Update User Profile', (WidgetTester tester) async {
        final result = await Quantum.auth.updateProfile({
          'displayName': 'Quantum Tester',
        });

        expect(result.isSuccess, isTrue);
        
        final session = await Quantum.auth.me();
        expect(session.data['claims']['displayName'], 'Quantum Tester');
      });

      testWidgets('Logout User', (WidgetTester tester) async {
        final result = await Quantum.auth.logout();
        expect(result.isSuccess, isTrue);
        
        final session = await Quantum.auth.me();
        expect(session.data['isAuthenticated'], isFalse);
      });

      testWidgets('Login User', (WidgetTester tester) async {
        final result = await Quantum.auth.login({
          'email': testEmail,
          'password': testPassword,
        });

        expect(result.isSuccess, isTrue, reason: 'Login failed: ${result.error?.message}');
        final session = await Quantum.auth.me();
        expect(session.data['isAuthenticated'], isTrue);
      });
    });

    // =========================================================================
    // FIRESTORE DATA ENGINE TESTS
    // =========================================================================
    group('Data Engine (FirebaseApiDriver - Firestore)', () {
      late String createdDocId;

      testWidgets('Create Document', (WidgetTester tester) async {
        final result = await Quantum.db.collection(testCollection).create({
          'title': 'Test Document 1',
          'score': 100,
          'active': true,
          'createdAt': DateTime.now().toIso8601String(),
        });

        expect(result.isSuccess, isTrue, reason: 'Create failed: ${result.error?.message}');
        expect(result.data['id'], isNotNull);
        createdDocId = result.data['id'];
      });

      testWidgets('Read Document By ID', (WidgetTester tester) async {
        final result = await Quantum.db.collection(testCollection).readById(createdDocId);
        
        expect(result.isSuccess, isTrue);
        expect(result.data['title'], 'Test Document 1');
        expect(result.data['score'], 100);
      });

      testWidgets('Update/Patch Document By ID', (WidgetTester tester) async {
        final result = await Quantum.db.collection(testCollection).patchById(createdDocId, {
          'score': 250,
          'updated': true,
        });

        expect(result.isSuccess, isTrue);

        final verify = await Quantum.db.collection(testCollection).readById(createdDocId);
        expect(verify.data['score'], 250);
        expect(verify.data['updated'], isTrue);
        expect(verify.data['title'], 'Test Document 1'); 
      });

      testWidgets('Count Aggregation', (WidgetTester tester) async {
        final result = await Quantum.db.collection(testCollection).count({});
        expect(result.isSuccess, isTrue);
        expect(result.data['count'], greaterThanOrEqualTo(1));
      });

      testWidgets('Global Variables (Set & Get)', (WidgetTester tester) async {
        final globalKey = 'test_settings_${generateRandomId()}';
        
        await Quantum.db.global(globalKey).set({'maintenanceMode': true});
        
        final result = await Quantum.db.global(globalKey).get();
        expect(result.isSuccess, isTrue);
        expect(result.data['maintenanceMode'], isTrue);
      });

      testWidgets('Delete Document', (WidgetTester tester) async {
        final result = await Quantum.db.collection(testCollection).deleteById(createdDocId);
        expect(result.isSuccess, isTrue);

        final verify = await Quantum.db.collection(testCollection).readById(createdDocId);
        expect(verify.isSuccess, isFalse); 
        expect(verify.error?.code, 'not_found');
      });
    });

    // =========================================================================
    // CRYPTO & CACHE ENGINE TESTS
    // =========================================================================
    group('Crypto & Cache Engine', () {
      testWidgets('AES-256 Encryption & Decryption', (WidgetTester tester) async {
        final secretMessage = {'credit_card': '1234-5678'};
        
        final encrypted = await Quantum.crypto.encrypt(secretMessage);
        expect(encrypted, isNot(contains('1234'))); 

        final decrypted = await Quantum.crypto.decrypt(encrypted);
        expect(decrypted['credit_card'], '1234-5678');
      });

      testWidgets('HMAC-SHA256 Signature Verification', (WidgetTester tester) async {
        final data = {'amount': 5000};
        final signature = await Quantum.crypto.sign(data);
        
        final isValid = await Quantum.crypto.verify(data, signature);
        expect(isValid, isTrue);

        final isInvalid = await Quantum.crypto.verify({'amount': 9000}, signature);
        expect(isInvalid, isFalse);
      });

      testWidgets('Memory Cache Set & Get', (WidgetTester tester) async {
        await Quantum.cache.set('test_cache_key', {'cached': true});
        final result = await Quantum.cache.get('test_cache_key');
        expect(result['cached'], isTrue);
      });
    });

    // =========================================================================
    // SECURE SDUI ENGINE TESTS
    // =========================================================================
    group('Secure SDUI Engine', () {
      late SecureSduiVault sduiVault;
      late SecureDisplayEngine displayEngine;

      setUpAll(() {
        final mockAuthEngine = QuantumAuthEngine(driver: MemoryAuthDriver());
        
        sduiVault = SecureSduiVault(
          store: MemoryLocalStore(),
          secret: 'TEST_SECRET_KEY_MUST_BE_32_BYTES_LONG_!!!',
          authEngine: mockAuthEngine,
        );

        displayEngine = SecureDisplayEngine(
          secret: 'TEST_SECRET_KEY_MUST_BE_32_BYTES_LONG_!!!',
        );
      });

      testWidgets('Store and Load Encrypted SDUI Layout', (WidgetTester tester) async {
        final pageKey = 'home_screen';
        final mockLayout = {'type': 'Column', 'children': []};
        
        await sduiVault.store(pageKey, mockLayout, version: 'v1.0.0');

        final loaded = await sduiVault.load(pageKey);
        expect(loaded, isNotNull);
        expect(loaded!['type'], 'Column');
      });

      testWidgets('Tamper Protection: Reject tampered Secure Display Payload', (WidgetTester tester) async {
        final data = {'balance': '\$10,000'};
        final timestamp = DateTime.now().millisecondsSinceEpoch;
        final nonce = 'random-nonce-123';
        
        final signatureInput = '$nonce:$timestamp:${jsonEncode(data)}';
        final validSignature = QuantumCipher.sign(signatureInput, 'TEST_SECRET_KEY_MUST_BE_32_BYTES_LONG_!!!');

        final payload = {
          'data': data,
          'timestamp': timestamp,
          'nonce': nonce,
          'signature': validSignature
        };

        // 1. Valid Payload passes
        final validResult = displayEngine.verifyAndConsume(payload);
        expect(validResult.isVerified, isTrue);

        // 2. Replay Attack fails
        final replayResult = displayEngine.verifyAndConsume(payload);
        expect(replayResult.isVerified, isFalse);

        // 3. Tampered Data fails
        final tamperedPayload = {
          ...payload,
          'data': {'balance': '\$99,999'}, 
          'nonce': 'new-nonce', 
        };
        
        final tamperedResult = displayEngine.verifyAndConsume(tamperedPayload);
        expect(tamperedResult.isVerified, isFalse);
      });
    });
  });
}