// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAca4kZKqScIYmmQbuoRlL5puX9zUuR4wU',
    appId: '1:388970688838:web:35505df4fee3ca84d9b547',
    messagingSenderId: '388970688838',
    projectId: 'fast-ability-437320-n7',
    authDomain: 'fast-ability-437320-n7.firebaseapp.com',
    storageBucket: 'fast-ability-437320-n7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgM9KoJdtY9xTaFxUqolUYJZOjaywIQiw',
    appId: '1:388970688838:android:cb13f9ddb8785527d9b547',
    messagingSenderId: '388970688838',
    projectId: 'fast-ability-437320-n7',
    storageBucket: 'fast-ability-437320-n7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3USMXlI3B-Z22MHRgsnjxSCSs_DVbCZw',
    appId: '1:388970688838:ios:a940d59410323caad9b547',
    messagingSenderId: '388970688838',
    projectId: 'fast-ability-437320-n7',
    storageBucket: 'fast-ability-437320-n7.firebasestorage.app',
    iosClientId: '388970688838-25gp5mtp4vd6e67igbp1h6p2232u7sum.apps.googleusercontent.com',
    iosBundleId: 'com.example.responsiveLayout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3USMXlI3B-Z22MHRgsnjxSCSs_DVbCZw',
    appId: '1:388970688838:ios:a940d59410323caad9b547',
    messagingSenderId: '388970688838',
    projectId: 'fast-ability-437320-n7',
    storageBucket: 'fast-ability-437320-n7.firebasestorage.app',
    iosClientId: '388970688838-25gp5mtp4vd6e67igbp1h6p2232u7sum.apps.googleusercontent.com',
    iosBundleId: 'com.example.responsiveLayout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAca4kZKqScIYmmQbuoRlL5puX9zUuR4wU',
    appId: '1:388970688838:web:5f58e3392491eb65d9b547',
    messagingSenderId: '388970688838',
    projectId: 'fast-ability-437320-n7',
    authDomain: 'fast-ability-437320-n7.firebaseapp.com',
    storageBucket: 'fast-ability-437320-n7.firebasestorage.app',
  );
}
