// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSATC-hLytH-BF2oQXFZVzmFePCS5bgok',
    appId: '1:1010031342818:web:d922c32215db9ceef55abb',
    messagingSenderId: '1010031342818',
    projectId: 'store-d6218',
    authDomain: 'store-d6218.firebaseapp.com',
    databaseURL: 'https://store-d6218-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'store-d6218.firebasestorage.app',
    measurementId: 'G-DXE14K380F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPvzMuxrOgxQvaW3UaiKQ4WVY3MGXOUdE',
    appId: '1:1010031342818:android:b895b0373a3d643bf55abb',
    messagingSenderId: '1010031342818',
    projectId: 'store-d6218',
    databaseURL: 'https://store-d6218-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'store-d6218.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuwZ9TzTPL78l5W2WuiZ-Mga1cO8NHUU8',
    appId: '1:1010031342818:ios:2d03038711551c73f55abb',
    messagingSenderId: '1010031342818',
    projectId: 'store-d6218',
    databaseURL: 'https://store-d6218-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'store-d6218.firebasestorage.app',
    iosBundleId: 'com.example.responsiveLayout',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuwZ9TzTPL78l5W2WuiZ-Mga1cO8NHUU8',
    appId: '1:1010031342818:ios:2d03038711551c73f55abb',
    messagingSenderId: '1010031342818',
    projectId: 'store-d6218',
    databaseURL: 'https://store-d6218-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'store-d6218.firebasestorage.app',
    iosBundleId: 'com.example.responsiveLayout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSATC-hLytH-BF2oQXFZVzmFePCS5bgok',
    appId: '1:1010031342818:web:f7251b11a6efd1fff55abb',
    messagingSenderId: '1010031342818',
    projectId: 'store-d6218',
    authDomain: 'store-d6218.firebaseapp.com',
    databaseURL: 'https://store-d6218-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'store-d6218.firebasestorage.app',
    measurementId: 'G-YBTDQNHBR7',
  );
}
