/*
 * ============================================================================
 * File: quantum_vm_catalog.dart
 * 
 * Description:
 * An auto-generated dictionary and introspection registry defining the taxonomy 
 * of the Quantum VM components. It supplies type information, parameter schemas, 
 * and property mappings required for visual editors, IDE validation, and low-code builders.
 * 
 * Key Components:
 * - QuantumVMCatalog: Contains static maps (e.g., omniCoreSubtypes, omniCoreFeaturePropTypes) 
 *   that define the valid configurations for every component type.
 * 
 * Dependencies/Relationships:
 * Referenced by quantum_vm.dart and the AST compiler to validate nodes and 
 * construct accurate schemas for dynamic blueprints.
 * 
 * Notes:
 * This file is highly structured and largely static; it should remain synchronized 
 * with the actual runtime component capabilities.
 * ============================================================================
 */
// quantum_vm_catalog.dart
// Auto-generated Dictionary and Introspection Registry for Quantum VM.
// Used for Visual Editors, Low-Code Builders, and IDE Validation.

class QuantumVMCatalog {
  static const Map<String, List<String>> omniCoreSubtypes =
        <String, List<String>>{
      'action': <String>[
        'double_tap',
        'focus',
        'gesture',
        'hover',
        'link',
        'long_press',
        'pointer',
        'press',
        'raw_pointer',
        'tap',
        'viewport'
      ],
      'accessibility': <String>['a11y', 'contrast', 'focus', 'keyboard', 'motion', 'semantics'],
      'box': <String>[
        'aspect',
        'builder',
        'col',
        'expanded',
        'flexible',
        'grid',
        'layer',
        'masonry',
        'matrix',
        'measure',
        'morph',
        'responsive',
        'row',
        'safe',
        'scroll',
        'shell',
        'split',
        'stack',
        'sticky',
        'surface',
        'viewport',
        'virtual_grid',
        'wrap'
      ],
      'canvas': <String>['draw', 'plot', 'shader', 'shape'],
      'chart': <String>[
        'line',
        'bar',
        'area',
        'pie',
        'donut',
        'radar',
        'scatter',
        'bubble',
        'candlestick',
        'funnel',
        'waterfall',
        'histogram',
        'gauge',
        'sparkline',
        'treemap',
        'sankey'
      ],
      'collab': <String>['awareness', 'cursor', 'lock', 'patch', 'presence'],
      'control': <String>[
        'accordion',
        'architecture',
        'flow',
        'form_scope',
        'machine',
        'optimistic',
        'reducer',
        'saga',
        'stepper',
        'tabs',
        'tca'
      ],
      'data': <String>[
        'aggregate',
        'cursor',
        'diff',
        'grid',
        'infinite',
        'kanban',
        'masonry',
        'paginated',
        'realtime',
        'repeat',
        'slice',
        'sliver',
        'sliver_plane',
        'stream',
        'table',
        'timeline',
        'virtual_scroll'
      ],
      'decoration': <String>[
        'badge',
        'blur',
        'border',
        'gradient',
        'rich',
        'ripple',
        'shadow',
        'skeleton',
        'span',
        'text'
      ],
      'field': <String>[
        'cell',
        'checkbox',
        'email',
        'multiline',
        'number',
        'password',
        'radio',
        'rich_text',
        'search',
        'slider',
        'tel',
        'text',
        'textarea',
        'toggle',
        'url'
      ],
      'hook': <String>[
        'atom',
        'bridge',
        'change',
        'delegate',
        'effect',
        'error_boundary',
        'guard',
        'interval',
        'lifecycle',
        'memo',
        'mount',
        'observable',
        'ref',
        'scope',
        'slice',
        'store'
      ],
      'media': <String>[
        'audio',
        'audio_visualizer',
        'avatar',
        'camera',
        'canvas_video',
        'icon',
        'path',
        'stream',
        'svg_path',
        'video',
        'webrtc'
      ],
      'portal': <String>[
        'action_sheet',
        'alert',
        'anchored_floating',
        'centered',
        'confirm',
        'context_menu',
        'context_panel',
        'dialog',
        'docked',
        'drawer',
        'dropdown',
        'edge_attached',
        'expandable_inline',
        'flyout',
        'form_modal',
        'full_page_sheet',
        'full_screen',
        'full_screen_surface',
        'immersive_editor',
        'inline_details',
        'inline_editor',
        'inspector',
        'lightbox',
        'left_panel',
        'menu',
        'mobile_sheet',
        'modal',
        'navigation_rail',
        'nonModal',
        'non_modal',
        'overlay',
        'overlay_entry',
        'persistent_drawer',
        'persistent_panel',
        'popover',
        'popup_modal',
        'right_panel',
        'sheet',
        'sidebar',
        'side_sheet',
        'toast',
        'temporary_overlay',
        'tooltip',
        'utility_panel',
        'window'
      ],
      'stream': <String>['multiplex', 'ring', 'sse', 'tick', 'ws'],
      'preset': <String>[],
      'layout': <String>[],
      'component': <String>[
        'define',
        'use',
        'instance',
        'render',
        'scoped',
        'link'
      ],
      'system': <String>[
        'async',
        'clipboard',
        'data_pipe',
        'debounce',
        'download',
        'geo',
        'haptic',
        'kinetic_pipe',
        'macro',
        'notification',
        'omega_macro',
        'repeater',
        'sensor',
        'share',
        'store_provider',
        'sync_scroll',
        'throttle',
        'ticker',
        'timer',
        'upload',
        'worker'
      ],
      'text': <String>['code', 'h1', 'h2', 'h3', 'label', 'rich'],
      'visual': <String>[
        'action',
        'animation',
        'box',
        'canvas',
        'chart',
        'compose',
        'connect',
        'control',
        'data',
        'decoration',
        'delegate',
        'field',
        'layer',
        'layout',
        'media',
        'overlay',
        'portal',
        'scene',
        'shell',
        'stack',
        'surface',
        'system',
        'preset',
        'text'
      ],
    };
  

  static final Map<String, Map<String, String>> omniCoreFeaturePropTypes =
        <String, Map<String, String>>{
      'action': <String, String>{
        'bindPressure': 'String',
        'bindState': 'String',
        'bindX': 'String',
        'bindY': 'String',
        'disabled': 'bool',
        'href': 'String',
        'icon': 'Widget',
        'loading': 'bool',
        'margin': 'List<dynamic>',
        'matrixBind': 'String',
        'onBlur': 'VoidCallback',
        'onClick': 'VoidCallback',
        'onDoubleTap': 'VoidCallback',
        'onEnter': 'VoidCallback',
        'onFocus': 'VoidCallback',
        'onHover': 'VoidCallback',
        'onKeyPress': 'VoidCallback',
        'onLongPress': 'VoidCallback',
        'onNavigate': 'VoidCallback',
        'onPan': 'VoidCallback',
        'onRelease': 'VoidCallback',
        'onScale': 'VoidCallback',
        'onTap': 'VoidCallback',
        'onUnhover': 'VoidCallback',
        'padding': 'List<dynamic>',
        'text': 'String',
        'value': 'String',
      },
      'animation': <String, String>{
        'animationType': 'String',
        'bind': 'String',
        'blur': 'double',
        'child': 'Widget',
        'color': 'Color',
        'count': 'int',
        'decimals': 'int',
        'delayMs': 'int',
        'durationMs': 'int',
        'first': 'Widget',
        'from': 'double',
        'fromX': 'double',
        'fromY': 'double',
        'height': 'double',
        'key': 'String',
        'radius': 'double',
        'second': 'Widget',
        'showFirst': 'bool',
        'steps': 'List<dynamic>',
        'tint': 'Color',
        'to': 'double',
        'toX': 'double',
        'toY': 'double',
        'width': 'double',
      },
      'box': <String, String>{
        'absorbPointer': 'bool',
        'animate': 'bool',
        'aspectBox': 'bool',
        'bind': 'String',
        'bottom': 'bool',
        'clip': 'bool',
        'clipKind': 'String',
        'cols': 'String',
        'constrained': 'bool',
        'curve': 'String',
        'dense': 'bool',
        'direction': 'String',
        'disabled': 'bool',
        'dragAxis': 'String',
        'dragData': 'String',
        'dragOpacity': 'double',
        'draggable': 'bool',
        'durationMs': 'int',
        'expand': 'bool',
        'fill': 'String',
        'flex': 'int',
        'floating': 'bool',
        'fractional': 'bool',
        'fractions': 'List<dynamic>',
        'gap': 'double',
        'gridCols': 'String',
        'gridRows': 'String',
        'height': 'double',
        'heightFactor': 'double',
        'heroFlight': 'bool',
        'heroTag': 'String',
        'hideOnDrag': 'bool',
        'id': 'dynamic',
        'ignorePointer': 'bool',
        'items': 'String',
        'justify': 'String',
        'left': 'bool',
        'lockAspect': 'bool',
        'longPressDraggable': 'bool',
        'margin': 'List<dynamic>',
        'matrix': 'String',
        'matrixBind': 'String',
        'maxHeight': 'double',
        'maxWidth': 'double',
        'minHeight': 'double',
        'minWidth': 'double',
        'offstage': 'bool',
        'onClick': 'VoidCallback',
        'opacity': 'double',
        'opacityBind': 'String',
        'padding': 'List<dynamic>',
        'pinned': 'bool',
        'ratio': 'double',
        'repaintBoundary': 'bool',
        'resize': 'bool',
        'right': 'bool',
        'rotate': 'bool',
        'rotateTurns': 'double',
        'rows': 'String',
        'scale': 'String',
        'scrollable': 'bool',
        'accessibleNavigation': 'bool',
        'excludeSemantics': 'bool',
        'focusable': 'bool',
        'highContrast': 'bool',
        'keyboardShortcut': 'String',
        'mergeSemantics': 'bool',
        'reduceMotion': 'bool',
        'semanticHint': 'String',
        'semanticLabel': 'String',
        'semanticValue': 'String',
        'semantics': 'bool',
        'textScaler': 'double',
        'snapGrid': 'double',
        'style': 'String',
        'top': 'bool',
        'transform': 'bool',
        'transformBind': 'String',
        'transition': 'String',
        'variant': 'String',
        'width': 'double',
        'widthFactor': 'double',
      },
      'canvas': <String, String>{
        'baseline': 'String',
        'bind': 'String',
        'color': 'Color',
        'commands': 'List<dynamic>',
        'fillColor': 'Color',
        'gapX': 'double',
        'mode': 'String',
        'scaleY': 'double',
        'shapeDef': 'Map<String, dynamic>',
        'src': 'String',
        'stepX': 'double',
        'thickness': 'double',
        'uniformBind': 'String',
      },
      'collab': <String, String>{
        'as': 'String',
        'key': 'String',
        'patch': 'Map<String, dynamic>',
        'resource': 'String',
        'room': 'String',
        'store': 'String',
        'userId': 'String',
      },
      'component': <String, String>{
        'animations': 'dynamic',
        'batch': 'dynamic',
        'cache': 'dynamic',
        'capabilities': 'dynamic',
        'component': 'dynamic',
        'computed': 'dynamic',
        'cursor': 'dynamic',
        'definition': 'dynamic',
        'description': 'String',
        'features': 'dynamic',
        'fields': 'dynamic',
        'guard': 'dynamic',
        'hooks': 'dynamic',
        'links': 'dynamic',
        'media': 'dynamic',
        'name': 'String',
        'network': 'dynamic',
        'omni': 'dynamic',
        'pagination': 'dynamic',
        'payload': 'dynamic',
        'permissions': 'dynamic',
        'policies': 'dynamic',
        'policy': 'dynamic',
        'presentation': 'dynamic',
        'preview': 'bool',
        'projection': 'dynamic',
        'props': 'dynamic',
        'render': 'bool',
        'resource': 'dynamic',
        'resources': 'dynamic',
        'runtime': 'dynamic',
        'select': 'dynamic',
        'slots': 'dynamic',
        'spec': 'dynamic',
        'state': 'dynamic',
        'stream': 'dynamic',
        'ui': 'dynamic',
        'variants': 'dynamic',
      },
      'connect': <String, String>{
        'activeRole': 'String',
        'altThreshold': 'double',
        'cancelThreshold': 'double',
        'channel': 'String',
        'contract': 'String',
        'fallback': 'String',
        'focusChannel': 'String',
        'heroTag': 'String',
        'longPressReveal': 'bool',
        'onAlt': 'VoidCallback',
        'onBack': 'VoidCallback',
        'onCancel': 'VoidCallback',
        'onClose': 'VoidCallback',
        'onCommit': 'VoidCallback',
        'onDismissed': 'VoidCallback',
        'onRefresh': 'VoidCallback',
        'phaseChannel': 'String',
        'roleNames': 'List<dynamic>',
        'scale': 'double',
        'text': 'String',
      },
      'control': <String, String>{
        'action': 'String',
        'actions': 'Map<String, dynamic>',
        'context': 'Map<String, dynamic>',
        'disposeFlowState': 'bool',
        'heroKey': 'String',
        'id': 'String',
        'initial': 'String',
        'initialIndex': 'int',
        'initialState': 'Map<String, dynamic>',
        'namespace': 'String',
        'optimisticData': 'Map<String, dynamic>',
        'rollbackOn': 'String',
        'routeKey': 'String',
        'selectionKey': 'String',
        'stateKey': 'String',
        'states': 'Map<String, dynamic>',
        'steps': 'List<dynamic>',
      },
      'data': <String, String>{
        'action': 'String',
        'as': 'String',
        'bind': 'String',
        'channel': 'String',
        'cols': 'String',
        'cursorKey': 'String',
        'direction': 'String',
        'empty': 'Widget',
        'gap': 'double',
        'header': 'Widget',
        'indexAs': 'String',
        'itemHeight': 'double',
        'key': 'String',
        'limit': 'int',
        'onEndReached': 'VoidCallback',
        'onReorder': 'VoidCallback',
        'pageSize': 'int',
        'pipeline': 'String',
        'searchBind': 'String',
        'sources': 'List<dynamic>',
        'start': 'int',
      },
      'decoration': <String, String>{
        'absorbPointer': 'bool',
        'beginColor': 'Color',
        'blur': 'double',
        'clip': 'bool',
        'color': 'Color',
        'endColor': 'Color',
        'fontSize': 'double',
        'height': 'double',
        'highlightColor': 'Color',
        'ignorePointer': 'bool',
        'label': 'String',
        'mergeStyle': 'String',
        'onDoubleTap': 'VoidCallback',
        'onHover': 'VoidCallback',
        'onLongPress': 'VoidCallback',
        'onTap': 'VoidCallback',
        'radius': 'double',
        'right': 'double',
        'sigma': 'double',
        'splashColor': 'Color',
        'spread': 'double',
        'style': 'String',
        'suppressParentData': 'bool',
        'textColor': 'Color',
        'tintColor': 'Color',
        'top': 'double',
        'width': 'double',
        'x': 'double',
        'y': 'double',
      },
      'field': <String, String>{
        'bind': 'String',
        'decimal': 'bool',
        'disabled': 'bool',
        'divisions': 'int',
        'id': 'String',
        'initialValue': 'bool',
        'label': 'String',
        'max': 'double',
        'maxLines': 'int',
        'min': 'double',
        'minLines': 'int',
        'placeholder': 'String',
        'prefix': 'Widget',
        'radius': 'double',
        'readOnly': 'bool',
        'suffix': 'Widget',
      },
      'hook': <String, String>{
        'action': 'dynamic',
        'as': 'String',
        'bind': 'String',
        'bridge': 'Map<String, dynamic>',
        'catch': 'Widget',
        'delegateProps': 'Map<String, dynamic>',
        'deps': 'List<dynamic>',
        'enabled': 'bool',
        'fallback': 'Widget',
        'finally': 'Widget',
        'id': 'String',
        'initial': 'dynamic',
        'initialState': 'Map<String, dynamic>',
        'key': 'String',
        'locals': 'dynamic',
        'memo': 'dynamic',
        'memoKey': 'dynamic',
        'ms': 'int',
        'onEffect': 'VoidCallback',
        'onMount': 'VoidCallback',
        'onUnmount': 'VoidCallback',
        'path': 'String',
        'payload': 'dynamic',
        'runOnMount': 'bool',
        'scope': 'Map<String, dynamic>',
        'store': 'String',
        'stream': 'String',
        'target': 'String',
        'try': 'Widget',
        'value': 'dynamic',
      },
      'layout': <String, String>{
        'align': 'String',
        'id': 'String',
        'layoutId': 'String',
        'match': 'String',
        'selectable': 'bool',
        'selectedStyle': 'String',
        'style': 'String',
        'text': 'String',
        'value': 'String',
      },
      'media': <String, String>{
        'allowBatch': 'bool',
        'audioUrl': 'String',
        'autoPlay': 'bool',
        'bind': 'String',
        'blurIntensity': 'double',
        'codePoint': 'int',
        'color': 'Color',
        'count': 'int',
        'error': 'Widget',
        'fill': 'Color',
        'fit': 'String',
        'fontFamily': 'String',
        'height': 'double',
        'id': 'String',
        'loop': 'bool',
        'mode': 'String',
        'path': 'String',
        'placeholder': 'Widget',
        'placeholderBase64': 'String',
        'poster': 'String',
        'progressive': 'bool',
        'quality': 'int',
        'roomId': 'String',
        'showSubtitles': 'bool',
        'size': 'double',
        'src': 'String',
        'stroke': 'Color',
        'strokeWidth': 'double',
        'subtitleOffsetMs': 'int',
        'subtitleUrl': 'String',
        'url': 'String',
        'width': 'double',
      },
      'portal': <String, String>{
        'align': 'String',
        'allowResize': 'bool',
        'barrierColor': 'Color',
        'barrierDismissible': 'bool',
        'barrierOpacity': 'double',
        'bgBlurSigma': 'double',
        'bgEffect': 'String',
        'bgZoomDepth': 'double',
        'clipSheet': 'bool',
        'content': 'Widget',
        'cornerRadius': 'double',
        'durationMs': 'double',
        'edge': 'String',
        'enableDrag': 'bool',
        'extrude3D': 'bool',
        'h': 'double',
        'isModal': 'bool',
        'matchAnchorWidth': 'bool',
        'resizeEdges': 'String',
        'rootBgColor': 'Color',
        'sheetAlignment': 'String',
        'sheetPadding': 'double',
        'sheetPaddingBottom': 'double',
        'sheetPaddingLeft': 'double',
        'sheetPaddingRight': 'double',
        'sheetPaddingTop': 'double',
        'showDragHandle': 'bool',
        'trigger': 'Widget',
        'triggerBind': 'String',
        'w': 'double',
        'x': 'double',
        'y': 'double',
      },
      'stream': <String, String>{
        'as': 'String',
        'bind': 'String',
        'capacity': 'int',
        'channels': 'List<dynamic>',
        'ms': 'int',
        'statusKey': 'String',
        'url': 'String',
      },
      'system': <String, String>{
        'action': 'String',
        'as': 'String',
        'autoStart': 'bool',
        'axis': 'String',
        'bind': 'String',
        'bindOutput': 'String',
        'bindSource': 'String',
        'bindX': 'String',
        'bindY': 'String',
        'copy': 'String',
        'damping': 'double',
        'direction': 'String',
        'indexAs': 'String',
        'initialState': 'Map<String, dynamic>',
        'interval': 'int',
        'mode': 'String',
        'ms': 'int',
        'onTick': 'VoidCallback',
        'outputBind': 'String',
        'params': 'Map<String, dynamic>',
        'pipeline': 'String',
        'props': 'Map<String, dynamic>',
        'size': 'int',
        'stiffness': 'double',
        'task': 'String',
        'preset': 'Map<String, dynamic>',
        'type': 'String',
      },
      'preset': <String, String>{
        'activeFill': 'String',
        'avatars': 'List<dynamic>',
        'backText': 'String',
        'bind': 'String',
        'categories': 'List<dynamic>',
        'cells': 'List<dynamic>',
        'children': 'List<dynamic>',
        'columns': 'List<dynamic>',
        'doneText': 'String',
        'dragData': 'String',
        'entries': 'List<dynamic>',
        'heroId': 'String',
        'index': 'int',
        'initialIndex': 'int',
        'intent': 'String',
        'itemScale': 'String',
        'itemStyle': 'String',
        'items': 'List<dynamic>',
        'label': 'String',
        'level': 'int',
        'magneto': 'bool',
        'magnetoIntensity': 'double',
        'maxVisible': 'int',
        'multiple': 'bool',
        'nextText': 'String',
        'onDone': 'List<dynamic>',
        'onDrop': 'VoidCallback',
        'onSelect': 'List<dynamic>',
        'onToggle': 'List<dynamic>',
        'prevText': 'String',
        'rows': 'List<dynamic>',
        'selected': 'bool',
        'steps': 'List<dynamic>',
        'subtitle': 'String',
      },
      'text': <String, String>{
        'maxLines': 'int',
        'overflow': 'String',
        'selectable': 'bool',
        'softWrap': 'bool',
        'style': 'String',
        'text': 'String',
        'value': 'String',
      },
      'visual': <String, String>{
        'animationType': 'String',
        'body': 'Widget',
        'boxType': 'String',
        'canvasType': 'dynamic',
        'chartType': 'String',
        'child': 'Widget',
        'chrome': 'Widget',
        'clip': 'bool',
        'connectType': 'dynamic',
        'content': 'Widget',
        'delegateProps': 'Map<String, dynamic>',
        'fieldType': 'String',
        'footer': 'Widget',
        'header': 'Widget',
        'isComplex': 'bool',
        'layout': 'String',
        'mediaType': 'String',
        'overlay': 'Widget',
        'portalType': 'dynamic',
        'systemType': 'String',
        'target': 'String',
        'templateName': 'dynamic',
        'willChange': 'bool',
      },
    };
  

  static final Map<String, Map<String, dynamic>> omniCoreFeatureCatalog =
        <String, Map<String, dynamic>>{
      'action': <String, dynamic>{
        'sourceFile': 'omni_cores/action_core.dart',
        'aliasCount': 10,
        'defineCount': 0,
        'propCount': 27,
        'featureProps': <String>[
          'bindPressure',
          'bindState',
          'bindX',
          'bindY',
          'disabled',
          'href',
          'icon',
          'loading',
          'margin',
          'matrixBind',
          'onBlur',
          'onClick',
          'onDoubleTap',
          'onEnter',
          'onFocus',
          'onHover',
          'onKeyPress',
          'onLongPress',
          'onNavigate',
          'onPan',
          'onRelease',
          'onScale',
          'onTap',
          'onUnhover',
          'padding',
          'text',
          'value',
        ],
        'propTypes': <String, String>{
          'bindPressure': 'String',
          'bindState': 'String',
          'bindX': 'String',
          'bindY': 'String',
          'disabled': 'bool',
          'href': 'String',
          'icon': 'Widget',
          'loading': 'bool',
          'margin': 'List<dynamic>',
          'matrixBind': 'String',
          'onBlur': 'VoidCallback',
          'onClick': 'VoidCallback',
          'onDoubleTap': 'VoidCallback',
          'onEnter': 'VoidCallback',
          'onFocus': 'VoidCallback',
          'onHover': 'VoidCallback',
          'onKeyPress': 'VoidCallback',
          'onLongPress': 'VoidCallback',
          'onNavigate': 'VoidCallback',
          'onPan': 'VoidCallback',
          'onRelease': 'VoidCallback',
          'onScale': 'VoidCallback',
          'onTap': 'VoidCallback',
          'onUnhover': 'VoidCallback',
          'padding': 'List<dynamic>',
          'text': 'String',
          'value': 'String',
        },
      },
      'animation': <String, dynamic>{
        'sourceFile': 'omni_cores/animation_core.dart',
        'aliasCount': 14,
        'defineCount': 0,
        'propCount': 24,
        'featureProps': <String>[
          'animationType',
          'bind',
          'blur',
          'child',
          'color',
          'count',
          'decimals',
          'delayMs',
          'durationMs',
          'first',
          'from',
          'fromX',
          'fromY',
          'height',
          'key',
          'radius',
          'second',
          'showFirst',
          'steps',
          'tint',
          'to',
          'toX',
          'toY',
          'width',
        ],
        'propTypes': <String, String>{
          'animationType': 'String',
          'bind': 'String',
          'blur': 'double',
          'child': 'Widget',
          'color': 'Color',
          'count': 'int',
          'decimals': 'int',
          'delayMs': 'int',
          'durationMs': 'int',
          'first': 'Widget',
          'from': 'double',
          'fromX': 'double',
          'fromY': 'double',
          'height': 'double',
          'key': 'String',
          'radius': 'double',
          'second': 'Widget',
          'showFirst': 'bool',
          'steps': 'List<dynamic>',
          'tint': 'Color',
          'to': 'double',
          'toX': 'double',
          'toY': 'double',
          'width': 'double',
        },
      },
      'box': <String, dynamic>{
        'sourceFile': 'omni_cores/box_core.dart',
        'aliasCount': 17,
        'defineCount': 0,
        'propCount': 72,
        'featureProps': <String>[
          'absorbPointer',
          'animate',
          'aspectBox',
          'bind',
          'bottom',
          'clip',
          'clipKind',
          'cols',
          'constrained',
          'curve',
          'dense',
          'direction',
          'disabled',
          'dragAxis',
          'dragData',
          'dragOpacity',
          'draggable',
          'durationMs',
          'expand',
          'fill',
          'flex',
          'floating',
          'fractional',
          'fractions',
          'gap',
          'gridCols',
          'gridRows',
          'height',
          'heightFactor',
          'heroFlight',
          'heroTag',
          'hideOnDrag',
          'id',
          'ignorePointer',
          'items',
          'justify',
          'left',
          'lockAspect',
          'longPressDraggable',
          'margin',
          'matrix',
          'matrixBind',
          'maxHeight',
          'maxWidth',
          'minHeight',
          'minWidth',
          'offstage',
          'onClick',
          'opacity',
          'opacityBind',
          'padding',
          'pinned',
          'ratio',
          'repaintBoundary',
          'resize',
          'right',
          'rotate',
          'rotateTurns',
          'rows',
          'scale',
          'scrollable',
          'accessibleNavigation',
          'excludeSemantics',
          'focusable',
          'highContrast',
          'keyboardShortcut',
          'mergeSemantics',
          'reduceMotion',
          'semanticHint',
          'semanticLabel',
          'semanticValue',
          'semantics',
          'textScaler',
          'snapGrid',
          'style',
          'top',
          'transform',
          'transformBind',
          'transition',
          'variant',
          'width',
          'widthFactor',
        ],
        'propTypes': <String, String>{
          'absorbPointer': 'bool',
          'animate': 'bool',
          'aspectBox': 'bool',
          'bind': 'String',
          'bottom': 'bool',
          'clip': 'bool',
          'clipKind': 'String',
          'cols': 'String',
          'constrained': 'bool',
          'curve': 'String',
          'dense': 'bool',
          'direction': 'String',
          'disabled': 'bool',
          'dragAxis': 'String',
          'dragData': 'String',
          'dragOpacity': 'double',
          'draggable': 'bool',
          'durationMs': 'int',
          'expand': 'bool',
          'fill': 'String',
          'flex': 'int',
          'floating': 'bool',
          'fractional': 'bool',
          'fractions': 'List<dynamic>',
          'gap': 'double',
          'gridCols': 'String',
          'gridRows': 'String',
          'height': 'double',
          'heightFactor': 'double',
          'heroFlight': 'bool',
          'heroTag': 'String',
          'hideOnDrag': 'bool',
          'id': 'dynamic',
          'ignorePointer': 'bool',
          'items': 'String',
          'justify': 'String',
          'left': 'bool',
          'lockAspect': 'bool',
          'longPressDraggable': 'bool',
          'margin': 'List<dynamic>',
          'matrix': 'String',
          'matrixBind': 'String',
          'maxHeight': 'double',
          'maxWidth': 'double',
          'minHeight': 'double',
          'minWidth': 'double',
          'offstage': 'bool',
          'onClick': 'VoidCallback',
          'opacity': 'double',
          'opacityBind': 'String',
          'padding': 'List<dynamic>',
          'pinned': 'bool',
          'ratio': 'double',
          'repaintBoundary': 'bool',
          'resize': 'bool',
          'right': 'bool',
          'rotate': 'bool',
          'rotateTurns': 'double',
          'rows': 'String',
          'scale': 'String',
          'scrollable': 'bool',
          'accessibleNavigation': 'bool',
          'excludeSemantics': 'bool',
          'focusable': 'bool',
          'highContrast': 'bool',
          'keyboardShortcut': 'String',
          'mergeSemantics': 'bool',
          'reduceMotion': 'bool',
          'semanticHint': 'String',
          'semanticLabel': 'String',
          'semanticValue': 'String',
          'semantics': 'bool',
          'textScaler': 'double',
          'snapGrid': 'double',
          'style': 'String',
          'top': 'bool',
          'transform': 'bool',
          'transformBind': 'String',
          'transition': 'String',
          'variant': 'String',
          'width': 'double',
          'widthFactor': 'double',
        },
      },
      'canvas': <String, dynamic>{
        'sourceFile': 'omni_cores/canvas_core.dart',
        'aliasCount': 1,
        'defineCount': 0,
        'propCount': 13,
        'featureProps': <String>[
          'baseline',
          'bind',
          'color',
          'commands',
          'fillColor',
          'gapX',
          'mode',
          'scaleY',
          'shapeDef',
          'src',
          'stepX',
          'thickness',
          'uniformBind',
        ],
        'propTypes': <String, String>{
          'baseline': 'String',
          'bind': 'String',
          'color': 'Color',
          'commands': 'List<dynamic>',
          'fillColor': 'Color',
          'gapX': 'double',
          'mode': 'String',
          'scaleY': 'double',
          'shapeDef': 'Map<String, dynamic>',
          'src': 'String',
          'stepX': 'double',
          'thickness': 'double',
          'uniformBind': 'String',
        },
      },
      'collab': <String, dynamic>{
        'sourceFile': 'omni_cores/collab_core.dart',
        'aliasCount': 4,
        'defineCount': 0,
        'propCount': 7,
        'featureProps': <String>[
          'as',
          'key',
          'patch',
          'resource',
          'room',
          'store',
          'userId',
        ],
        'propTypes': <String, String>{
          'as': 'String',
          'key': 'String',
          'patch': 'Map<String, dynamic>',
          'resource': 'String',
          'room': 'String',
          'store': 'String',
          'userId': 'String',
        },
      },
      'component': <String, dynamic>{
        'sourceFile': 'quantum_vm_components.dart',
        'aliasCount': 4,
        'defineCount': 0,
        'propCount': 38,
        'featureProps': <String>[
          'animations',
          'batch',
          'cache',
          'capabilities',
          'component',
          'computed',
          'cursor',
          'definition',
          'description',
          'features',
          'fields',
          'guard',
          'hooks',
          'links',
          'media',
          'name',
          'network',
          'omni',
          'pagination',
          'payload',
          'permissions',
          'policies',
          'policy',
          'presentation',
          'preview',
          'projection',
          'props',
          'render',
          'resource',
          'resources',
          'runtime',
          'select',
          'slots',
          'spec',
          'state',
          'stream',
          'ui',
          'variants',
        ],
        'propTypes': <String, String>{
          'animations': 'dynamic',
          'batch': 'dynamic',
          'cache': 'dynamic',
          'capabilities': 'dynamic',
          'component': 'dynamic',
          'computed': 'dynamic',
          'cursor': 'dynamic',
          'definition': 'dynamic',
          'description': 'String',
          'features': 'dynamic',
          'fields': 'dynamic',
          'guard': 'dynamic',
          'hooks': 'dynamic',
          'links': 'dynamic',
          'media': 'dynamic',
          'name': 'String',
          'network': 'dynamic',
          'omni': 'dynamic',
          'pagination': 'dynamic',
          'payload': 'dynamic',
          'permissions': 'dynamic',
          'policies': 'dynamic',
          'policy': 'dynamic',
          'presentation': 'dynamic',
          'preview': 'bool',
          'projection': 'dynamic',
          'props': 'dynamic',
          'render': 'bool',
          'resource': 'dynamic',
          'resources': 'dynamic',
          'runtime': 'dynamic',
          'select': 'dynamic',
          'slots': 'dynamic',
          'spec': 'dynamic',
          'state': 'dynamic',
          'stream': 'dynamic',
          'ui': 'dynamic',
          'variants': 'dynamic',
        },
      },
      'connect': <String, dynamic>{
        'sourceFile': 'omni_cores/connect_core.dart',
        'aliasCount': 11,
        'defineCount': 2,
        'propCount': 20,
        'featureProps': <String>[
          'activeRole',
          'altThreshold',
          'cancelThreshold',
          'channel',
          'contract',
          'fallback',
          'focusChannel',
          'heroTag',
          'longPressReveal',
          'onAlt',
          'onBack',
          'onCancel',
          'onClose',
          'onCommit',
          'onDismissed',
          'onRefresh',
          'phaseChannel',
          'roleNames',
          'scale',
          'text',
        ],
        'propTypes': <String, String>{
          'activeRole': 'String',
          'altThreshold': 'double',
          'cancelThreshold': 'double',
          'channel': 'String',
          'contract': 'String',
          'fallback': 'String',
          'focusChannel': 'String',
          'heroTag': 'String',
          'longPressReveal': 'bool',
          'onAlt': 'VoidCallback',
          'onBack': 'VoidCallback',
          'onCancel': 'VoidCallback',
          'onClose': 'VoidCallback',
          'onCommit': 'VoidCallback',
          'onDismissed': 'VoidCallback',
          'onRefresh': 'VoidCallback',
          'phaseChannel': 'String',
          'roleNames': 'List<dynamic>',
          'scale': 'double',
          'text': 'String',
        },
      },
      'control': <String, dynamic>{
        'sourceFile': 'omni_cores/control_core.dart',
        'aliasCount': 10,
        'defineCount': 0,
        'propCount': 17,
        'featureProps': <String>[
          'action',
          'actions',
          'context',
          'disposeFlowState',
          'heroKey',
          'id',
          'initial',
          'initialIndex',
          'initialState',
          'namespace',
          'optimisticData',
          'rollbackOn',
          'routeKey',
          'selectionKey',
          'stateKey',
          'states',
          'steps',
        ],
        'propTypes': <String, String>{
          'action': 'String',
          'actions': 'Map<String, dynamic>',
          'context': 'Map<String, dynamic>',
          'disposeFlowState': 'bool',
          'heroKey': 'String',
          'id': 'String',
          'initial': 'String',
          'initialIndex': 'int',
          'initialState': 'Map<String, dynamic>',
          'namespace': 'String',
          'optimisticData': 'Map<String, dynamic>',
          'rollbackOn': 'String',
          'routeKey': 'String',
          'selectionKey': 'String',
          'stateKey': 'String',
          'states': 'Map<String, dynamic>',
          'steps': 'List<dynamic>',
        },
      },
      'data': <String, dynamic>{
        'sourceFile': 'omni_cores/data_core.dart',
        'aliasCount': 2,
        'defineCount': 0,
        'propCount': 21,
        'featureProps': <String>[
          'action',
          'as',
          'bind',
          'channel',
          'cols',
          'cursorKey',
          'direction',
          'empty',
          'gap',
          'header',
          'indexAs',
          'itemHeight',
          'key',
          'limit',
          'onEndReached',
          'onReorder',
          'pageSize',
          'pipeline',
          'searchBind',
          'sources',
          'start',
        ],
        'propTypes': <String, String>{
          'action': 'String',
          'as': 'String',
          'bind': 'String',
          'channel': 'String',
          'cols': 'String',
          'cursorKey': 'String',
          'direction': 'String',
          'empty': 'Widget',
          'gap': 'double',
          'header': 'Widget',
          'indexAs': 'String',
          'itemHeight': 'double',
          'key': 'String',
          'limit': 'int',
          'onEndReached': 'VoidCallback',
          'onReorder': 'VoidCallback',
          'pageSize': 'int',
          'pipeline': 'String',
          'searchBind': 'String',
          'sources': 'List<dynamic>',
          'start': 'int',
        },
      },
      'decoration': <String, dynamic>{
        'sourceFile': 'omni_cores/decoration_core.dart',
        'aliasCount': 3,
        'defineCount': 0,
        'propCount': 29,
        'featureProps': <String>[
          'absorbPointer',
          'beginColor',
          'blur',
          'clip',
          'color',
          'endColor',
          'fontSize',
          'height',
          'highlightColor',
          'ignorePointer',
          'label',
          'mergeStyle',
          'onDoubleTap',
          'onHover',
          'onLongPress',
          'onTap',
          'radius',
          'right',
          'sigma',
          'splashColor',
          'spread',
          'style',
          'suppressParentData',
          'textColor',
          'tintColor',
          'top',
          'width',
          'x',
          'y',
        ],
        'propTypes': <String, String>{
          'absorbPointer': 'bool',
          'beginColor': 'Color',
          'blur': 'double',
          'clip': 'bool',
          'color': 'Color',
          'endColor': 'Color',
          'fontSize': 'double',
          'height': 'double',
          'highlightColor': 'Color',
          'ignorePointer': 'bool',
          'label': 'String',
          'mergeStyle': 'String',
          'onDoubleTap': 'VoidCallback',
          'onHover': 'VoidCallback',
          'onLongPress': 'VoidCallback',
          'onTap': 'VoidCallback',
          'radius': 'double',
          'right': 'double',
          'sigma': 'double',
          'splashColor': 'Color',
          'spread': 'double',
          'style': 'String',
          'suppressParentData': 'bool',
          'textColor': 'Color',
          'tintColor': 'Color',
          'top': 'double',
          'width': 'double',
          'x': 'double',
          'y': 'double',
        },
      },
      'field': <String, dynamic>{
        'sourceFile': 'omni_cores/field_core.dart',
        'aliasCount': 10,
        'defineCount': 0,
        'propCount': 16,
        'featureProps': <String>[
          'bind',
          'decimal',
          'disabled',
          'divisions',
          'id',
          'initialValue',
          'label',
          'max',
          'maxLines',
          'min',
          'minLines',
          'placeholder',
          'prefix',
          'radius',
          'readOnly',
          'suffix',
        ],
        'propTypes': <String, String>{
          'bind': 'String',
          'decimal': 'bool',
          'disabled': 'bool',
          'divisions': 'int',
          'id': 'String',
          'initialValue': 'bool',
          'label': 'String',
          'max': 'double',
          'maxLines': 'int',
          'min': 'double',
          'minLines': 'int',
          'placeholder': 'String',
          'prefix': 'Widget',
          'radius': 'double',
          'readOnly': 'bool',
          'suffix': 'Widget',
        },
      },
      'hook': <String, dynamic>{
        'sourceFile': 'omni_cores/hook_core.dart',
        'aliasCount': 9,
        'defineCount': 0,
        'propCount': 30,
        'featureProps': <String>[
          'action',
          'as',
          'bind',
          'bridge',
          'catch',
          'delegateProps',
          'deps',
          'enabled',
          'fallback',
          'finally',
          'id',
          'initial',
          'initialState',
          'key',
          'locals',
          'memo',
          'memoKey',
          'ms',
          'onEffect',
          'onMount',
          'onUnmount',
          'path',
          'payload',
          'runOnMount',
          'scope',
          'store',
          'stream',
          'target',
          'try',
          'value',
        ],
        'propTypes': <String, String>{
          'action': 'dynamic',
          'as': 'String',
          'bind': 'String',
          'bridge': 'Map<String, dynamic>',
          'catch': 'Widget',
          'delegateProps': 'Map<String, dynamic>',
          'deps': 'List<dynamic>',
          'enabled': 'bool',
          'fallback': 'Widget',
          'finally': 'Widget',
          'id': 'String',
          'initial': 'dynamic',
          'initialState': 'Map<String, dynamic>',
          'key': 'String',
          'locals': 'dynamic',
          'memo': 'dynamic',
          'memoKey': 'dynamic',
          'ms': 'int',
          'onEffect': 'VoidCallback',
          'onMount': 'VoidCallback',
          'onUnmount': 'VoidCallback',
          'path': 'String',
          'payload': 'dynamic',
          'runOnMount': 'bool',
          'scope': 'Map<String, dynamic>',
          'store': 'String',
          'stream': 'String',
          'target': 'String',
          'try': 'Widget',
          'value': 'dynamic',
        },
      },
      'layout': <String, dynamic>{
        'sourceFile': 'quantum_vm_core/quantum_vm_layout.dart',

        'aliasCount': 38,
        'defineCount': 0,
        'propCount': 9,
        'featureProps': <String>[
          'align',
          'id',
          'layoutId',
          'match',
          'selectable',
          'selectedStyle',
          'style',
          'text',
          'value',
        ],
        'propTypes': <String, String>{
          'align': 'String',
          'id': 'String',
          'layoutId': 'String',
          'match': 'String',
          'selectable': 'bool',
          'selectedStyle': 'String',
          'style': 'String',
          'text': 'String',
          'value': 'String',
        },
      },
      'media': <String, dynamic>{
        'sourceFile': 'omni_cores/media_core.dart',
        'aliasCount': 4,
        'defineCount': 0,
        'propCount': 32,
        'featureProps': <String>[
          'allowBatch',
          'audioUrl',
          'autoPlay',
          'bind',
          'blurIntensity',
          'codePoint',
          'color',
          'count',
          'error',
          'fill',
          'fit',
          'fontFamily',
          'textScaler',
          'height',
          'id',
          'loop',
          'mode',
          'path',
          'placeholder',
          'placeholderBase64',
          'poster',
          'progressive',
          'quality',
          'roomId',
          'showSubtitles',
          'size',
          'src',
          'stroke',
          'strokeWidth',
          'subtitleOffsetMs',
          'subtitleUrl',
          'url',
          'width',
        ],
        'propTypes': <String, String>{
          'allowBatch': 'bool',
          'audioUrl': 'String',
          'autoPlay': 'bool',
          'bind': 'String',
          'blurIntensity': 'double',
          'codePoint': 'int',
          'color': 'Color',
          'count': 'int',
          'error': 'Widget',
          'fill': 'Color',
          'fit': 'String',
          'fontFamily': 'String',
          'textScaler': 'double',
          'height': 'double',
          'id': 'String',
          'loop': 'bool',
          'mode': 'String',
          'path': 'String',
          'placeholder': 'Widget',
          'placeholderBase64': 'String',
          'poster': 'String',
          'progressive': 'bool',
          'quality': 'int',
          'roomId': 'String',
          'showSubtitles': 'bool',
          'size': 'double',
          'src': 'String',
          'stroke': 'Color',
          'strokeWidth': 'double',
          'subtitleOffsetMs': 'int',
          'subtitleUrl': 'String',
          'url': 'String',
          'width': 'double',
        },
      },
      'portal': <String, dynamic>{
        'sourceFile': 'omni_cores/portal_core.dart',
        'aliasCount': 6,
        'defineCount': 0,
        'propCount': 32,
        'featureProps': <String>[
          'align',
          'allowResize',
          'barrierColor',
          'barrierDismissible',
          'barrierOpacity',
          'bgBlurSigma',
          'bgEffect',
          'bgZoomDepth',
          'clipSheet',
          'content',
          'cornerRadius',
          'durationMs',
          'edge',
          'enableDrag',
          'extrude3D',
          'h',
          'isModal',
          'matchAnchorWidth',
          'resizeEdges',
          'rootBgColor',
          'sheetAlignment',
          'sheetPadding',
          'sheetPaddingBottom',
          'sheetPaddingLeft',
          'sheetPaddingRight',
          'sheetPaddingTop',
          'showDragHandle',
          'trigger',
          'triggerBind',
          'w',
          'x',
          'y',
        ],
        'propTypes': <String, String>{
          'align': 'String',
          'allowResize': 'bool',
          'barrierColor': 'Color',
          'barrierDismissible': 'bool',
          'barrierOpacity': 'double',
          'bgBlurSigma': 'double',
          'bgEffect': 'String',
          'bgZoomDepth': 'double',
          'clipSheet': 'bool',
          'content': 'Widget',
          'cornerRadius': 'double',
          'durationMs': 'double',
          'edge': 'String',
          'enableDrag': 'bool',
          'extrude3D': 'bool',
          'h': 'double',
          'isModal': 'bool',
          'matchAnchorWidth': 'bool',
          'resizeEdges': 'String',
          'rootBgColor': 'Color',
          'sheetAlignment': 'String',
          'sheetPadding': 'double',
          'sheetPaddingBottom': 'double',
          'sheetPaddingLeft': 'double',
          'sheetPaddingRight': 'double',
          'sheetPaddingTop': 'double',
          'showDragHandle': 'bool',
          'trigger': 'Widget',
          'triggerBind': 'String',
          'w': 'double',
          'x': 'double',
          'y': 'double',
        },
      },
      'stream': <String, dynamic>{
        'sourceFile': 'omni_cores/stream_core.dart',
        'aliasCount': 4,
        'defineCount': 0,
        'propCount': 7,
        'featureProps': <String>[
          'as',
          'bind',
          'capacity',
          'channels',
          'ms',
          'statusKey',
          'url',
        ],
        'propTypes': <String, String>{
          'as': 'String',
          'bind': 'String',
          'capacity': 'int',
          'channels': 'List<dynamic>',
          'ms': 'int',
          'statusKey': 'String',
          'url': 'String',
        },
      },
      'system': <String, dynamic>{
        'sourceFile': 'omni_cores/system_core.dart',
        'aliasCount': 4,
        'defineCount': 0,
        'propCount': 27,
        'featureProps': <String>[
          'action',
          'as',
          'autoStart',
          'axis',
          'bind',
          'bindOutput',
          'bindSource',
          'bindX',
          'bindY',
          'copy',
          'damping',
          'direction',
          'indexAs',
          'initialState',
          'interval',
          'mode',
          'ms',
          'onTick',
          'outputBind',
          'params',
          'pipeline',
          'props',
          'size',
          'stiffness',
          'task',
          'template',
          'type',
        ],
        'propTypes': <String, String>{
          'action': 'String',
          'as': 'String',
          'autoStart': 'bool',
          'axis': 'String',
          'bind': 'String',
          'bindOutput': 'String',
          'bindSource': 'String',
          'bindX': 'String',
          'bindY': 'String',
          'copy': 'String',
          'damping': 'double',
          'direction': 'String',
          'indexAs': 'String',
          'initialState': 'Map<String, dynamic>',
          'interval': 'int',
          'mode': 'String',
          'ms': 'int',
          'onTick': 'VoidCallback',
          'outputBind': 'String',
          'params': 'Map<String, dynamic>',
          'pipeline': 'String',
          'props': 'Map<String, dynamic>',
          'size': 'int',
          'stiffness': 'double',
          'task': 'String',
          'preset': 'Map<String, dynamic>',
          'type': 'String',
        },
      },
      'preset': <String, dynamic>{
        'sourceFile': 'omni_cores/preset_core.dart',
        'aliasCount': 51,
        'defineCount': 0,
        'propCount': 34,
        'featureProps': <String>[
          'activeFill',
          'avatars',
          'backText',
          'bind',
          'categories',
          'cells',
          'children',
          'columns',
          'doneText',
          'dragData',
          'entries',
          'heroId',
          'index',
          'initialIndex',
          'intent',
          'itemScale',
          'itemStyle',
          'items',
          'label',
          'level',
          'magneto',
          'magnetoIntensity',
          'maxVisible',
          'multiple',
          'nextText',
          'onDone',
          'onDrop',
          'onSelect',
          'onToggle',
          'prevText',
          'rows',
          'selected',
          'steps',
          'subtitle',
        ],
        'propTypes': <String, String>{
          'activeFill': 'String',
          'avatars': 'List<dynamic>',
          'backText': 'String',
          'bind': 'String',
          'categories': 'List<dynamic>',
          'cells': 'List<dynamic>',
          'children': 'List<dynamic>',
          'columns': 'List<dynamic>',
          'doneText': 'String',
          'dragData': 'String',
          'entries': 'List<dynamic>',
          'heroId': 'String',
          'index': 'int',
          'initialIndex': 'int',
          'intent': 'String',
          'itemScale': 'String',
          'itemStyle': 'String',
          'items': 'List<dynamic>',
          'label': 'String',
          'level': 'int',
          'magneto': 'bool',
          'magnetoIntensity': 'double',
          'maxVisible': 'int',
          'multiple': 'bool',
          'nextText': 'String',
          'onDone': 'List<dynamic>',
          'onDrop': 'VoidCallback',
          'onSelect': 'List<dynamic>',
          'onToggle': 'List<dynamic>',
          'prevText': 'String',
          'rows': 'List<dynamic>',
          'selected': 'bool',
          'steps': 'List<dynamic>',
          'subtitle': 'String',
        },
      },
      'text': <String, dynamic>{
        'sourceFile': 'omni_cores/text_core.dart',
        'aliasCount': 0,
        'defineCount': 0,
        'propCount': 7,
        'featureProps': <String>[
          'maxLines',
          'overflow',
          'selectable',
          'softWrap',
          'style',
          'text',
          'value',
        ],
        'propTypes': <String, String>{
          'maxLines': 'int',
          'overflow': 'String',
          'selectable': 'bool',
          'softWrap': 'bool',
          'style': 'String',
          'text': 'String',
          'value': 'String',
        },
      },
      'visual': <String, dynamic>{
        'sourceFile': 'omni_cores/visual_core.dart',
        'aliasCount': 5,
        'defineCount': 0,
        'propCount': 23,
        'featureProps': <String>[
          'animationType',
          'body',
          'boxType',
          'canvasType',
          'chartType',
          'child',
          'chrome',
          'clip',
          'connectType',
          'content',
          'delegateProps',
          'fieldType',
          'footer',
          'header',
          'isComplex',
          'layout',
          'mediaType',
          'overlay',
          'portalType',
          'systemType',
          'target',
          'templateName',
          'willChange',
        ],
        'propTypes': <String, String>{
          'animationType': 'String',
          'body': 'Widget',
          'boxType': 'String',
          'canvasType': 'dynamic',
          'chartType': 'String',
          'child': 'Widget',
          'chrome': 'Widget',
          'clip': 'bool',
          'connectType': 'dynamic',
          'content': 'Widget',
          'delegateProps': 'Map<String, dynamic>',
          'fieldType': 'String',
          'footer': 'Widget',
          'header': 'Widget',
          'isComplex': 'bool',
          'layout': 'String',
          'mediaType': 'String',
          'overlay': 'Widget',
          'portalType': 'dynamic',
          'systemType': 'String',
          'target': 'String',
          'templateName': 'dynamic',
          'willChange': 'bool',
        },
      },
    };
  

  static const List<Map<String, String>> dslOperators = <Map<String, String>>[
      {
        'name': r'$define',
        'description':
            'Declare compile-time named macros. Children can invoke them via \$call or by type name.',
        'valueType': 'Map<String, Node>',
      },
      {
        'name': r'$let',
        'description':
            'Declare compile-time local variables, resolved structurally from the compile-env.',
        'valueType': 'Map<String, dynamic>',
      },
      {
        'name': r'$if',
        'description':
            'Conditional render guard. Falsy conditions remove the node from the tree.',
        'valueType': 'dynamic',
      },
      {
        'name': r'$repeat',
        'description':
            'List renderer. Iterates the bound path, exposing each item via `as` binding.',
        'valueType': 'String (bind path)',
      },
      {
        'name': r'$call',
        'description':
            'Invoke a previously \$define-d macro by name, forwarding caller props.',
        'valueType': 'String (macro name)',
      },
      {
        'name': r'$switch',
        'description':
            'Multi-branch compile-time switch. Matches `\$switch` value against `cases` keys.',
        'valueType': 'dynamic',
      },
      {
        'name': r'$async',
        'description':
            'Async data loader. Fires an action and renders loading/data/error slots.',
        'valueType': 'Map<String, dynamic>',
      },
      {
        'name': r'$stream',
        'description': 'Reactive stream subscription binding.',
        'valueType': 'String | Map',
      },
      {
        'name': r'$machine',
        'description':
            'Finite state machine node. Wraps children in a control:machine scope.',
        'valueType': 'Map<String, dynamic>',
      },
      {
        'name': r'$portal',
        'description': 'Renders content into a named portal overlay entry.',
        'valueType': 'String (portal name)',
      },
      {
        'name': r'$watch',
        'description': 'Mark a reactive signal dependency for the node.',
        'valueType': 'String (signal path)',
      },
      {
        'name': r'$try',
        'description':
            'Error boundary shorthand. Maps to hook:error_boundary slots.',
        'valueType': 'Node',
      },
      {
        'name': r'$layout',
        'description':
            'Named-area CSS-grid-style layout. Rows are ASCII art strings mapping slot names.',
        'valueType': 'List<String> (rows)',
      },
      {
        'name': r'$compose',
        'description':
            'Attach behavior mixins to the node via the `behaviors` prop.',
        'valueType': 'List<String>',
      },
      {
        'name': r'$apply',
        'description': 'Apply prop/style overrides to all direct children.',
        'valueType': 'Map<String, dynamic>',
      },
      {
        'name': r'$scope',
        'description': 'Prefix all descendant bind paths with a namespace scope.',
        'valueType': 'String (scope prefix)',
      },
      {
        'name': r'$spread',
        'description': 'Spread a runtime object into the node\'s props.',
        'valueType': 'String (bind path)',
      },
      {
        'name': r'$throttle',
        'description':
            'Throttle descendant event handling to at most once per N ms.',
        'valueType': 'int (ms)',
      },
      {
        'name': r'$debounce',
        'description': 'Debounce descendant event handling by N ms.',
        'valueType': 'int (ms)',
      },
      {
        'name': r'$parallel',
        'description': 'Fan-out: render up to 8 concurrent child nodes.',
        'valueType': 'List<Node>',
      },
      {
        'name': r'$reactive_map',
        'description': 'Animated diff list â€” only re-renders changed items.',
        'valueType': 'String | Map',
      },
      {
        'name': r'$classes',
        'description': 'Declare @ClassName shorthand aliases for style strings.',
        'valueType': 'Map<String, String>',
      },
    ];
  
}
