import 'dart:io';
import 'package:yaml/yaml.dart';
void main(List<String> args) {
  final repoRoot = Directory.current;
  final manifestRoot = Directory('${repoRoot.path}/docs_tests/yaml/by-file');
  if (!manifestRoot.existsSync()) {
    stderr.writeln('Manifest directory not found: ${manifestRoot.path}');
    exit(1);
  }

  for (final entity in manifestRoot.listSync(recursive: true, followLinks: false)) {
    if (entity is! File || !entity.path.endsWith('.yaml')) continue;
    if (entity.path.endsWith('INDEX.yaml') || entity.path.endsWith('README.md')) continue;
    final manifest = _load(entity);
    final sourcePath = manifest['source_metadata']['path'] as String;
    final fileLabel = sourcePath;
    final manifestRel = _rel(entity.path, repoRoot.path);
    final testFile = _testFileFor(repoRoot.path, sourcePath);
    final sourceImport = _relativeImport(testFile.parent.path, '${repoRoot.path}/quantum.dart');

    testFile.parent.createSync(recursive: true);
    testFile.writeAsStringSync(_buildTestFile(
      sourcePath: sourcePath,
      manifestPath: manifestRel,
      sourceImport: sourceImport,
      fileLabel: fileLabel,
      groupCount: (manifest['groups'] as List?)?.length ?? 0,
      rowCount: _countRows(manifest),
      profile: manifest['profile']?.toString() ?? '',
    ));
  }
}

Map<String, dynamic> _load(File file) {
  final parsed = loadYaml(file.readAsStringSync());
  return _native(parsed) as Map<String, dynamic>;
}

dynamic _native(dynamic value) {
  if (value is YamlMap) {
    final map = <String, dynamic>{};
    for (final entry in value.entries) {
      map[entry.key.toString()] = _native(entry.value);
    }
    return map;
  }
  if (value is YamlList) return value.map(_native).toList(growable: false);
  return value;
}

int _countRows(Map<String, dynamic> manifest) {
  final groups = manifest['groups'];
  if (groups is! List) return 0;
  var total = 0;
  for (final g in groups) {
    if (g is Map && g['rows'] is List) total += (g['rows'] as List).length;
  }
  return total;
}

String _buildTestFile({
  required String sourcePath,
  required String manifestPath,
  required String sourceImport,
  required String fileLabel,
  required int groupCount,
  required int rowCount,
  required String profile,
}) {
  return '''// Generated by tool/generate_quantum_tests.dart
// Source: $sourcePath
// Manifest: $manifestPath
// Profile: $profile
// Groups: $groupCount
// Rows: $rowCount
// This file is intentionally a thin runner around the shared manifest suite.

import 'package:flutter_test/flutter_test.dart';
import '$sourceImport';
import '../../support/quantum_generated_suite.dart';
void main() {
  defineQuantumManifestSuite(
    manifestPath: '$manifestPath',
    sourcePath: '$sourcePath',
    fileLabel: '$fileLabel',
  );
}
''';
}

String _relativeImport(String fromDir, String target) {
  final from = Uri.file(fromDir).pathSegments.where((e) => e.isNotEmpty).toList();
  final to = Uri.file(target).pathSegments.where((e) => e.isNotEmpty).toList();
  var i = 0;
  while (i < from.length && i < to.length && from[i] == to[i]) {
    i++;
  }
  final up = List.filled(from.length - i, '..');
  final down = to.sublist(i);
  return [...up, ...down].join('/');
}

File _testFileFor(String repoRoot, String sourcePath) {
  final testRelative = sourcePath.replaceAll('.dart', '_test.dart');
  return File('$repoRoot/test/generated/$testRelative');
}

String _rel(String target, String fromDir) {
  final from = Uri.file(fromDir).pathSegments.where((e) => e.isNotEmpty).toList();
  final to = Uri.file(target).pathSegments.where((e) => e.isNotEmpty).toList();
  var i = 0;
  while (i < from.length && i < to.length && from[i] == to[i]) {
    i++;
  }
  final up = List.filled(from.length - i, '..');
  final down = to.sublist(i);
  return [...up, ...down].join('/');
}
